exercicio_1: exercicio_1.c
	gcc exercicio_1.c -o exercicio_1

exercicio_2: exercicio_2.c
	gcc exercicio_2.c -o exercicio_2 -lm

exercicio_3: exercicio_3.c
	gcc exercicio_3.c -o exercicio_3

limpar:
	rm exercicio_1 exercicio_2 exercicio_3
